### ISSUE TITLE
Packages publishing

### ISSUE THREAD

**Issue by MeerKatDev** [eigerco/uniffi-zcash-lib#132]
After [conversations](https://forum.zcashcommunity.com/t/zcash-uniffi-library-rfp/43468/28), here is the plan forward:
 - [x] Publish the Python library to pypy
 - [x] Publish the Ruby library to Rubygems
 - [x] Publish the Kotlin library to Maven
 - [ ] Publish the Swift library to swiftpackageregistry
 - [ ] Add a disclaimer to the README about community maintenance mode

**Comment by eloylp** [comment]
Alright ! taking over this. 

One of the things i was wondering a bit, is about agreeing on version code. Do the version needs to reflect in some way the wrapped `librustzcash` versions ? My answer to this question would be that no, as they can follow completely different release cycles. I am thinking on the following strategy:

* Start with the first version `0.1.0` , which means the API can break anytime for the moment.
* If someone wants to know which librustzcash versions are under the hood, its enough to check `Cargo.toml` files of an specific `uniffi-zcash-lib` (this repo) version.
* Add a [changelog](https://keepachangelog.com/en/1.0.0/) in the repo for keeping track of the changes.

Does it makes sense @MeerKatDev  ?

**Comment by MeerKatDev** [comment]
There are going to be details on the Readme about this.
