### ISSUE TITLE
Consider Adding REGTEST network

### ISSUE THREAD

**Issue by pacu** [eigerco/uniffi-zcash-lib#134]
I'm working on integration tests that work over REGTEST. 

The python bindings would have been the best tool for the job since I need to quickly generate addresses that will receive the funds and don't care much about spinning up a wallet. 

Sadly that's not available.

````Python
class ZcashConsensusParameters(enum.Enum): 
    MAIN_NETWORK = 1
    
    TEST_NETWORK = 2
````

Proposed API:

````Python
class ZcashConsensusParameters(enum.Enum): 
    MAIN_NETWORK = 1
    
    TEST_NETWORK = 2
    
    REGTEST_NETWORK =3
````

**Comment by MeerKatDev** [comment]
Thank you @pacu , we will have a look at it

**Comment by MeerKatDev** [comment]
@pacu looks like it isn't present on librustzcash, so we can't port it either. There are indeed constants bound to the regtest network, but it isn't under the enum you mentioned, so as long as they don't add it, we cannot either.

**Comment by pacu** [comment]
Thanks for pointing this out @MeerKatDev, I'll try so see if I can squeeze this into my upcoming milestones so that you folks can support REGTEST too
