### ISSUE TITLE
Encode a transaction to binary/string

### ISSUE THREAD

**Issue by hauleth** [eigerco/uniffi-zcash-lib#32]

**Comment by eloylp** [comment]
Not sure if there is an available method to serialize it to a string. But we already implemented in #31 a `to_bytes()` method, which corresponds to [write()](https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L809) in librustzcash. Probably we could close this, but lets wait for other inputs.

**Comment by zduny** [comment]
> Not sure if there is an available method to serialize it to a string. But we already implemented in #31 a `to_bytes()` method, which corresponds to [write()](https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L809) in librustzcash. Probably we could close this, but lets wait for other inputs.

Like mentioned in other issue if struct has `read` and/or `write` methods - use them to implement `from_bytes` and `to_bytes` - we can't really make `read` and `write` cross the ffi barrier, but at least we can provide `from_bytes`, `to_bytes` methods as a (slightly less performant) alternative.

**Comment by eloylp** [comment]
Closing this, as we already have an implementation of `to_bytes()` , forged at #31 .
