### ISSUE TITLE
Try to mimic the zcash ecosystem package structure

### ISSUE THREAD

**Issue by eloylp** [eigerco/uniffi-zcash-lib#47]
### Context

We are currently putting all the objects in the same [UDL namespace](https://github.com/eloylp/uniffi-zcash-lib/blob/main/lib/uniffi_backend_keys/src/backend_keys.udl).

The zcash ecosystem works by separating the different key types (`Orchard`, `Sapling`) on their own modules, and leaving the `unified` ones (which are more generic) at the same level. Heres the module structure:

* `zcash_client_backend::keys::UnifiedSpendingKey`
* `zcash_client_backend::keys::UnifiedFullViewingKey`

* `zcash_client_backend::keys::sapling::DiversifiableFullViewingKey`
* `orchard::keys::FullViewingKey`

### Goal

It would be great to mimic this separation of concerns in all the verticals of the project: 

* Check capabilities of Mozilla `UDL` file (namespaces)
* Check Rust wrapping code (the code we use for FFI)
* Organize the tests in the different languages.

**Comment by eloylp** [comment]
Related to this issue, maybe it would be a good idea to wait for #46  , as we will have a real case to solve in code.

**Comment by zduny** [comment]
The original idea was to have separate `UDL` namespaces matching those used in `librustzcash` (and possibly separate crate in workspace for each).

Problem is the `uniffi-rs` feature making it possible - [external types](https://mozilla.github.io/uniffi-rs/udl/ext_types.html) currently only works for Kotlin and Swift - which I verified in my [personal example project](https://github.com/zduny/uniffi-example).

I'm currently verifying if extending support to Python and Ruby is feasible in reasonable time.

But even if it is - there are some caveats - separation of those namespaces is somewhat superficial - when using types from multiple namespaces `uniffi-rs` doesn't use full paths - it simply imports them at the top.
What it means is that you still have to be careful to not use the same names for different types across multiple namespaces.

Nevertheless, using multiple namespaces would allow us a better organization of our code so I believe it is still worth pursuing...

**Comment by eloylp** [comment]
Many thanks for all the context @zduny . I see, thats a pitty. Lets defer this one for now while we research.

**Comment by zduny** [comment]
This can be closed - we've decided to use split `.udl` files and "glue" them together in `build.rs` script.
