### ISSUE TITLE
Create tutorials/docs per each language (API use)

### ISSUE THREAD

**Issue by eloylp** [eigerco/uniffi-zcash-lib#49]
Once we have a more complete API, start creating the needed tutorials/documentation for each language.

The library user should be able to read and understand tutorials (in English language) taking into account patterns of functionality practiced by the single community

Tutorials are needed for:
- Generate the private key and derive the other keys with a step-by-step approach (answer to why do we generate this key?)
- Build a transaction
- Wallet handling

**Comment by eloylp** [comment]
I think it would be good to provide always complete code examples (including imports) that can be easily copy/pasted and just "work".

**Comment by eloylp** [comment]
Analysing a bit now the things we want to add in tutorials.  I think there are 2 main things. The conceptual part of the tutorials, of "Why do we use this" and the code.

In order to not repeat the conceptual part, i think it would be good to have an `example` directory in the root of the project and reference the examples in the conceptual part.

**Comment by eloylp** [comment]
I also liked the language example per tab way, seen in [geeksforgeeks.org](https://www.geeksforgeeks.org/calculate-depth-full-binary-tree-preorder/)

![image](https://github.com/eigerco/uniffi-zcash-lib/assets/5852187/93f08e99-b766-42d3-99d3-58f58e201a32)

Imagine the example of creating a transaction. We could put the explanation at the beginning, which will be the same for all languages and then, add each language code example to the respective tab.

I don't know if there is some static web template with that tabs we could load in in something like [Github pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites) . Leaving here the idea :thinking:

**Comment by MeerKatDev** [comment]
Looks good @eloylp
