### ISSUE TITLE
Automatically expose bindings API surface documentation

### ISSUE THREAD

**Issue by eloylp** [eigerco/uniffi-zcash-lib#50]
### Problem

Once we have the bindings generated for the different languages, theres no easy way to discover the API surface. 

Probably developers of each language community will go directly to their respective language documentation. That increases a lot the importance of the each language binding API documentation, till the point it can determine the level of adoption.

### A possible idea

Each language has its own doc generation tools/servers for generating API documentation:

* Kotlin -  Has [dokka](https://github.com/Kotlin/dokka)
* Python - Has [pydoc](https://docs.python.org/3/library/pydoc.html)
* Ruby  - Has [rdocs](https://github.com/ruby/rdoc)
* Swift - Has [jazzy](https://github.com/realm/jazzy)

Investigate if it would be possible, once we have the generated bindings, to invoke this docs generation tools as part of the CI pipeline. Even try to omit the Mozillas UniFFI proxy code of the bindings in the docs.

### Previous related work

An effort [was done](https://github.com/eigerco/uniffi-rs/issues) in order to make the Mozillas UniFFi lib to be capable of propagating the code documentation from the Rust wrapper code to each language binding. We would be generating binding API docs using that input.

**Comment by eloylp** [comment]
This could be a transversal issue. Let me know your thoughts @hauleth @zduny .

**Comment by zduny** [comment]
Yes, we'll have to include documentation generation to CI (to check if it works fine) and update the main `README.md` with explanation of how users can generate documentation themselves.

Regarding publication of documentation - it's related to distribution of the bindings themselves - we have to figure out if we're going to publish distributables to foreign-language-specific registries - like some Maven repository for Kotlin, Swift Package Manager for Swift etc... - and if there are related services available (like Rust's https://docs.rs/) for distributing documentation.

**Comment by eloylp** [comment]
Do we have an issue we can link here to generate discussion there @zduny ?

**Comment by zduny** [comment]
Related: https://github.com/eigerco/uniffi-zcash-lib/issues/54
I think it's OK to close this issue and move further discussion there.

**Comment by eloylp** [comment]
More progress on this:

* For the swift part, looks like `jazzy` its only available for Macos. We are falling back into [swift doc](https://github.com/SwiftDocOrg/swift-doc) until another alternative arises.
* We have developed the needed CLI commands, included those necessary for setting up the environment before docs generation.
* We enabled github pages in the repository, and we are currently trying to push the generated docs into the static server via Github actions.

All of this progress can be checked here:  https://github.com/eigerco/uniffi-zcash-lib/pull/128

### How does the docs generation looks like from a developer perspective ?

By the moment the docs needs to be generated and committed in the repo at  `lib/docs`  before each release. That is , the releaser needs to generate the docs by invoking the CLI:
```bash
$ cargo run -p uniffi-zcash-cli docgen python -v 0.0.0
$ cargo run -p uniffi-zcash-cli docgen ruby -v 0.0.0
$ cargo run -p uniffi-zcash-cli docgen kotlin -v 0.0.0
$ cargo run -p uniffi-zcash-cli docgen swift -v 0.0.0
```

The above commands will automatically generate the following project structure under `lib/docs`:

```bash
.
├── index.html
├── kotlin
│   ├── 0.0.0
│   └── index.html
├── python
│   ├── 0.0.0
│   └── index.html
├── ruby
│   ├── 0.0.0
│   └── index.html
└── swift
    ├── 0.0.0
    └── index.html
```

There is a folder per version, containing the generated docs. Each version will be added and committed incrementally on each release.

The `index.html` files contains javascript code that helps on presenting a minimal index for users. Such files will be present from the beginning in the repo.

Ultimatelly , the CI will upload the `/docs` folder to the static web server.

This way, all the code plus the docs are at the same commit. I think this is good as a first solution, but probably on future steps, i would move the docs to a completely isolated repo.

**Comment by eloylp** [comment]
Alright i tried to test the github pages CI publication with the example Github provides, but [its failing](https://github.com/eigerco/uniffi-zcash-lib/actions/runs/5201433077) without leaving any trace we can analyze. This is a beta feature from Github, so i am unsure what to expect here. Another alternative, would to manually commit in a separate branch that the Github pages server "listens" for publishing content. Anyway :

Another problem, is the size of the docs. The Kotlin docs weight around `32 MB` per version. That could be too much for a code repository. Probably its better to upload them to some kind of storage like [S3](https://aws.amazon.com/es/s3/). Normally, this object storage systems also provide optional static web servers for free for serving the bucket content.

I consider all of the above options to be very custom per each case. It will depend on final client infrastructure preferences. So i would leave it as it [is now](https://github.com/eigerco/uniffi-zcash-lib/issues/50#issuecomment-1580947945), as the docs can be automatically generated by the CLI. Its just needed to choose where to put them.

We will leave the CI steps just deactivated in case someone wants to enable them and try again.
