### ISSUE TITLE
Code reorganization

### ISSUE THREAD

**Issue by zduny** [eigerco/uniffi-zcash-lib#57]
Considering `uniffi-rs`'s lack of support for [external types](https://mozilla.github.io/uniffi-rs/udl/ext_types_external.html) for Ruby and Python we're forced to use a single `UDL` namespace.

Therefore we have to reorganize existing code:
- [x] Update dependencies - first we need to update dependencies to `librustzcash` (and related) crates and modify (if needed) existing code to work with updated dependencies,
- [x] Cleanup workspace - there will be two members in workspace: 
 - `uniffi-zcash` - crate with our bindings,
 - `uniffi-bindgen` - crate related to [bindings generation](https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html) - already exists, nothing has to be changed.
- [x] Split code in `lib.rs` into modules (loosely) matching namespaces in [librustzcash](https://github.com/zcash/librustzcash) (see [example project](https://github.com/zduny/uniffi-example/tree/main/bindings-simple) for reference)
- [x] Split `.udl` files to match those modules, join them together in `build.rs` script (see [example project](https://github.com/zduny/uniffi-example/tree/main/bindings-simple) for reference)
- [x] Code cleanup - see below
- [x] Tests cleanup - see below
- [x] Add wiki page explaining motivation of using a single namespace (lack of support for external types for Ruby and Python, superficial `uniffi-rs` namespacing - type names still can't collide, potentially faster builds, lack of potential issues that could emerge due to crate and namespace split).

**Comment by zduny** [comment]
Additionally modify/cleanup existing code to match following convention (we'll stick to it from now on):

## Use simple tuple structs:
This:
```rust
pub struct ZcashDiversifier(Diversifier);
```

**NOT** this:
```rust
pub struct ZcashDiversifier {
    inner: Diversifier,
}
```

## Import and use name directly
Considering code split, I believe we can get away with simply doing this:
```rust
use zcash_primitives::legacy::TransparentAddress;

// ...

pub struct ZcashTransparentAddress(TransparentAddress);
```

**Instead** of using longer paths like:
```rust
pub struct ZcashTransparentAddress(zcash_primitives::legacy::TransparentAddress);
```

## Constructors

### Default constructors
Constructor named `new` in `librustzcash` - simply use a `constructor` in `.udl`.

### Named constructors
Constructor with a name different than `new` use `Name={constructor name}` attribute in `.udl`:
```
interface ZcashOrchardDiversifier {
  [Name=from_bytes, Throws=ZcashError]
  constructor(sequence<u8> bytes);
};
```
**Unless** it's the *only* constructor - then use `new` in bindings Rust code and `.udl`. 

### Constructors returning optional 
Constructors returning `Option` - use `Result` in bindings and `ZcashError` in `.udl` (chose or create a new error that seems most appropriate) - `uniffi-rs` does not support constructors returning optional types.
```
/* zcash_primitives::legacy::keys::AccountPrivKey */
interface ZcashAccountPrivKey {

// ...

  [Name=from_bytes, Throws=ZcashError]
  constructor(sequence<u8> data);
```

**Comment by hauleth** [comment]
Doesn't Kotlin and Swift have some test runners that would do that automatically? It is weird that there is no such thing there already.

**Comment by zduny** [comment]
With Java (and Kotlin) you usually have a fully set up project with test dependencies, so it's difficult... `.kts` is a Kotlin *script* file - so not even a "proper" Kotlin.

With Swift - I have to try if proper test setup will work (again test dependencies may be a problem).

**Comment by zduny** [comment]
@hauleth thanks for resolving "Add wiki page explaining motivation of using a single namespace" task.
