### ISSUE TITLE
Review repo documentation (wiki, readme)

### ISSUE THREAD

**Issue by eloylp** [eigerco/uniffi-zcash-lib#81]
Extend a bit more the documentation thinking in newcomers.

**Comment by eloylp** [comment]
Some progress here. The following changes were done in the [wiki](https://github.com/eigerco/uniffi-zcash-lib/wiki):

* Created the [project structure section](https://github.com/eigerco/uniffi-zcash-lib/wiki/Project-structure), with motivations about design decisions.

* Created [api surface analysis section](https://github.com/eigerco/uniffi-zcash-lib/wiki/Api-surface-analysis) , to condense/share all the API knowledge there.

* Finally, added a recommended tour through documentation to the [wiki home page](https://github.com/eigerco/uniffi-zcash-lib/wiki), with the above sections among others.

In order to properly notice the wiki home page in the README.md, https://github.com/eigerco/uniffi-zcash-lib/pull/82 was created.

All this elements should be reviewed by reviewers, in order to ensure the information/organization is correct and intuitive. Moving to review !

**Comment by zduny** [comment]
_To fix_: typos in [project structure section](https://github.com/eigerco/uniffi-zcash-lib/wiki/Project-structure) - "its" to "is" (where appropriate), "its" to "it's" (again - where appropriate), "dont" to "don't".
